version: '3.0'
services:
  postgres:
    restart: unless-stopped
    image: postgres:10
    container_name: enhanced_city_db
    environment:
      - POSTGRES_USER=${user}
      - POSTGRES_PASSWORD=${password}
      - POSTGRES_DB=${dbname}
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  app:
    container_name: enhanced_city_api
    build: .
    ports:
      - 1525:5000
    volumes:
      - .:/api
    depends_on:
      - postgres
